using Emberline.Cam.Raster;
using Emberline.Cam.Vector;
using Emberline.Core.Documents;
using Emberline.Core.Geometry;
using Emberline.Core.Jobs;
using Emberline.Core.Machines;
using Emberline.GCode;

namespace Emberline.Cam;

public sealed record CamOptions
{
    /// <summary>Curve flattening tolerance in millimetres.</summary>
    public double Tolerance { get; init; } = Curves.DefaultTolerance;

    /// <summary>Return to the work origin when the job finishes.</summary>
    public bool ReturnToOrigin { get; init; } = true;

    /// <summary>Emit the machine profile's init block at the top of the job.</summary>
    public bool EmitPreamble { get; init; } = true;

    /// <summary>Dither settings for image layers.</summary>
    public Raster.Dither.Options DitherOptions { get; init; } = Raster.Dither.Options.Default;

    /// <summary>Report progress while generating — a large raster can take a few seconds.</summary>
    public IProgress<(string Stage, double Fraction)>? Progress { get; init; }

    /// <summary>Rotary attachment, if one is fitted.</summary>
    public RotarySetup Rotary { get; init; } = RotarySetup.Disabled;

    public static readonly CamOptions Default = new();
}

public sealed record CamResult(
    JobDefinition Job,
    Toolpath Toolpath,
    TimeEstimate Estimate,
    IReadOnlyList<ValidationIssue> Issues)
{
    public bool CanRun => !JobValidator.HasBlockingIssue(Issues);
}

/// <summary>
/// Document plus machine, in — runnable job, out.
///
/// The pipeline the PRD describes: artwork, geometry, operations, CAM, toolpaths,
/// G-code, validation. Layers run in their declared order, and every layer's
/// settings are resolved against the machine profile here rather than being
/// scattered through the generators, so there is one place where "80 % power"
/// becomes "S800".
/// </summary>
public static class CamPipeline
{
    /// <summary>
    /// Warn when the job runs off the material.
    ///
    /// A warning rather than an error: overhanging the blank is occasionally
    /// deliberate — scoring a fold line past the edge, or engraving a sheet that
    /// will be trimmed afterwards — and the machine is perfectly capable of doing
    /// it. What it must not do is happen silently, because the usual cause is
    /// artwork that was never centred and the first sign is a scorched bed.
    ///
    /// For a round blank this is measured against the bounding square, so it is
    /// the optimistic answer: art can fit the square and still overhang the disc.
    /// The text says so rather than implying a precision it does not have.
    /// </summary>
    private static ValidationIssue? WorkpieceWarning(Design design, Toolpath toolpath)
    {
        var workpiece = design.Workpiece;
        if (!workpiece.IsSet || toolpath.Count == 0) return null;

        // Where the laser actually fires, not where the head travels. The rapid
        // back to the work origin at the end of every job would otherwise put the
        // toolpath's bounds at the corner of the bed and warn on every job.
        var bounds = toolpath.BurnBounds;
        if (bounds.IsEmpty) return null;

        var (x, y) = workpiece.Overhang(bounds);
        if (x <= 0.05 && y <= 0.05) return null;

        var detail = $"The job overruns the {workpiece.Summary} workpiece by {x:0.#} mm in X and {y:0.#} mm in Y. " +
                     "Centre the artwork on the workpiece, or make it smaller.";

        if (workpiece.Shape == WorkpieceShape.Circle)
        {
            detail += " This is measured against the square around the circle, so anything near a corner may overhang by more.";
        }

        return new ValidationIssue(ValidationSeverity.Warning, "Job runs off the workpiece", detail);
    }

    public static CamResult Generate(
        Design design,
        MachineProfile machine,
        CamOptions? options = null,
        IReadOnlyDictionary<int, double>? machineSettings = null,
        bool isHomed = true)
    {
        var o = options ?? CamOptions.Default;
        var lines = new List<string>
        {
            "; Generated by Emberline",
            $"; Machine: {machine.DisplayName} ({machine.LaserWatts:0.#} W, {machine.BedWidthMm:0}×{machine.BedHeightMm:0} mm)",
            $"; Document: {design.Name}",
            $"; Created: {DateTimeOffset.UtcNow:u}",
        };

        if (o.EmitPreamble) lines.AddRange(machine.InitCommands);

        if (o.Rotary.Enabled)
        {
            lines.Add($"; {o.Rotary.Describe()}");
            foreach (var warning in o.Rotary.Check(design.Bounds.Height)) lines.Add($"; WARNING: {warning}");
        }

        var layers = design.OrderedLayers.ToList();
        var layerIndex = 0;
        var sourceFiles = new List<string>();

        foreach (var layer in layers)
        {
            layerIndex++;
            o.Progress?.Report(($"Layer {layerIndex} of {layers.Count}: {layer.Name}", (double)layerIndex / Math.Max(1, layers.Count)));

            var shapes = design.ShapesOnLayer(layer).ToList();
            if (shapes.Count == 0) continue;

            lines.Add(string.Empty);
            lines.Add($"; ---- {layer.Name} · {layer.Operation} · {layer.SpeedMmMin:0} mm/min @ {layer.PowerPercent:0.#}% × {layer.Passes} ----");

            if (layer.AirAssist && machine.Capabilities.HasFlag(MachineCapabilities.AirAssist))
            {
                lines.Add(machine.AirAssistOnCommand);
            }

            // Images always raster-engrave, whatever the layer's nominal operation:
            // there is no sensible way to "cut" a photograph.
            foreach (var image in shapes.OfType<ImageShape>())
            {
                if (image.SourcePath is not null) sourceFiles.Add(image.SourcePath);
                lines.AddRange(GenerateImage(image, layer, machine, o));
            }

            var vectorShapes = shapes.Where(s => s is not ImageShape).ToList();
            if (vectorShapes.Count > 0)
            {
                var outlines = vectorShapes.SelectMany(s => s.GetOutlines(o.Tolerance)).Where(p => p.Count >= 2).ToList();
                if (outlines.Count > 0) lines.AddRange(GenerateVector(outlines, layer, machine));
            }

            if (layer.AirAssist && machine.Capabilities.HasFlag(MachineCapabilities.AirAssist))
            {
                lines.Add(machine.AirAssistOffCommand);
            }
        }

        lines.Add(string.Empty);
        lines.Add("M5");
        if (o.ReturnToOrigin) lines.Add("G0 X0 Y0");
        lines.Add("; end of job");

        if (o.Rotary.IsUsable)
        {
            o.Progress?.Report(("Applying rotary scale", 0.8));
            lines = ApplyRotary(lines, o.Rotary);
        }

        o.Progress?.Report(("Interpreting toolpath", 0.85));

        var toolpath = GcodeInterpreter.Interpret(lines, new InterpreterOptions
        {
            MaxSpindle = machine.MaxSpindleValue,
        });

        o.Progress?.Report(("Estimating time", 0.93));

        var limits = machineSettings is not null
            ? MachineLimits.FromSettings(machineSettings, LimitsFromProfile(machine))
            : LimitsFromProfile(machine);

        var estimate = TimeEstimator.Estimate(toolpath, limits);
        var issues = JobValidator.Validate(toolpath, machine, isHomed, machineSettings).ToList();
        if (WorkpieceWarning(design, toolpath) is { } overhang) issues.Add(overhang);

        o.Progress?.Report(("Done", 1.0));

        var job = new JobDefinition
        {
            Name = design.Name,
            Lines = lines,
            Bounds = toolpath.BurnBounds,
            EstimatedDuration = estimate.Total,
            MachineProfileId = machine.Id,
            SourceFiles = sourceFiles.Distinct().ToList(),
        };

        return new CamResult(job, toolpath, estimate, issues);
    }

    /// <summary>
    /// Rescale the rotary axis in an already-generated program.
    ///
    /// Done as a text pass over the finished lines rather than inside every
    /// generator: the scale applies to whatever the axis ends up being commanded,
    /// including the raster lead-ins and the return-to-origin, and doing it in one
    /// place means no generator can forget.
    /// </summary>
    internal static List<string> ApplyRotary(List<string> lines, RotarySetup rotary)
    {
        var scale = rotary.ScaleFactor;
        var axis = char.ToUpperInvariant(rotary.Axis);
        var result = new List<string>(lines.Count);

        foreach (var line in lines)
        {
            if (line.Length == 0 || line[0] == ';')
            {
                result.Add(line);
                continue;
            }

            var index = line.IndexOf(axis);
            if (index < 0)
            {
                result.Add(line);
                continue;
            }

            var sb = new System.Text.StringBuilder(line.Length + 8);
            for (var i = 0; i < line.Length; i++)
            {
                if (char.ToUpperInvariant(line[i]) != axis)
                {
                    sb.Append(line[i]);
                    continue;
                }

                // Read the number that follows the axis letter.
                var start = i + 1;
                var end = start;
                if (end < line.Length && (line[end] == '-' || line[end] == '+')) end++;
                while (end < line.Length && (char.IsDigit(line[end]) || line[end] == '.')) end++;

                if (end == start || !double.TryParse(line.AsSpan(start, end - start),
                        System.Globalization.NumberStyles.Float,
                        System.Globalization.CultureInfo.InvariantCulture, out var value))
                {
                    sb.Append(line[i]);
                    continue;
                }

                sb.Append(axis).Append((value * scale).ToString("0.####", System.Globalization.CultureInfo.InvariantCulture));
                i = end - 1;
            }

            result.Add(sb.ToString());
        }

        return result;
    }

    private static MachineLimits LimitsFromProfile(MachineProfile machine) => new()
    {
        MaxRateX = machine.MaxSpeedMmMin,
        MaxRateY = machine.MaxSpeedMmMin,
        AccelerationX = machine.AccelerationX,
        AccelerationY = machine.AccelerationY,
        JunctionDeviation = machine.JunctionDeviation,
    };

    private static IEnumerable<string> GenerateImage(ImageShape image, Layer layer, MachineProfile machine, CamOptions o)
    {
        var bounds = image.Bounds;

        var rasterOptions = new RasterOptions
        {
            WidthMm = bounds.Width,
            HeightMm = bounds.Height,
            OriginX = bounds.MinX,
            OriginY = bounds.MinY,
            LineIntervalMm = layer.LineIntervalMm,
            Scan = ScanPattern.Horizontal,
            Bidirectional = layer.Bidirectional,
            OverscanMm = layer.OverscanMm,
            FeedMmMin = Math.Min(layer.SpeedMmMin, machine.MaxSpeedMmMin),
            TravelFeedMmMin = machine.TravelSpeedMmMin,
            MinPowerPercent = layer.MinPowerPercent,
            MaxPowerPercent = layer.PowerPercent,
            MaxSpindle = machine.MaxSpindleValue,
            DynamicPower = machine.Capabilities.HasFlag(MachineCapabilities.LaserMode),
            Passes = layer.Passes,
            EmitHeader = false,
        };

        // A hard-threshold or greyscale layer wants the picture; a Cut or Score
        // layer holding an image almost certainly wants its outline traced instead,
        // but that is a document-level decision, so raster is the honest default.
        var result = RasterEngraver.Process(image.Source, image.Adjustments, o.DitherOptions, rasterOptions);

        yield return $"; image {image.Name}: {image.Source.Width}×{image.Source.Height} px, " +
                     $"{result.Rows} rows, {result.BurnMoves} burn moves";

        foreach (var line in result.Lines) yield return line;
    }

    private static IEnumerable<string> GenerateVector(List<Polyline> outlines, Layer layer, MachineProfile machine)
    {
        var vectorOptions = VectorEngraver.OptionsFor(layer, machine);

        // Overlapping shapes are merged into their combined outline first, or the
        // beam runs through the middle of the finished piece. Skipped when nothing
        // overlaps, which is the usual case and not worth the work.
        if (layer.MergeOverlaps && PathBooleans.AnyOverlap(outlines))
        {
            outlines = PathBooleans.Union(outlines);
        }

        if (layer.Operation != OperationKind.Fill)
        {
            return VectorEngraver.Generate(outlines, vectorOptions);
        }

        var closed = outlines.Where(p => p.IsClosed && p.Count >= 3).ToList();
        if (closed.Count == 0)
        {
            // Nothing enclosed, so there is nothing to fill. Outline it instead of
            // silently producing an empty layer.
            return VectorEngraver.Generate(outlines, vectorOptions);
        }

        var fillPaths = layer.FillStrategy == FillStrategy.Offset
            ? HatchFill.GenerateOffsetFill(closed, layer.LineIntervalMm)
            : HatchFill.Generate(closed, new HatchOptions
            {
                SpacingMm = layer.LineIntervalMm,
                AngleDegrees = layer.FillAngleDeg,
                CrossHatch = layer.FillStrategy == FillStrategy.CrossHatch,
                Bidirectional = layer.Bidirectional,
            });

        // Hatch lines are already in scan order; re-optimising would undo the
        // serpentine ordering that makes a fill fast.
        var lines = VectorEngraver.Generate(fillPaths, vectorOptions with
        {
            OptimiseTravel = false,
            InsideOutFirst = false,
        }).ToList();

        return lines;
    }

    /// <summary>
    /// Generate a power-versus-speed test grid.
    ///
    /// The single most useful thing a laser owner can burn, and the honest answer to
    /// "what settings should I use for this material" — no lookup table beats ten
    /// minutes and a scrap offcut.
    /// </summary>
    public static CamResult GenerateTestGrid(
        MachineProfile machine,
        double[] powerPercents,
        double[] speeds,
        double cellSizeMm = 10,
        double gapMm = 3,
        double originX = 10,
        double originY = 10,
        int passes = 1)
    {
        var design = new Design { Name = "Material test grid" };
        var layer = Layer.CreateDefault(OperationKind.Fill, 0);
        design.Layers.Add(layer);

        var lines = new List<string>
        {
            "; Emberline material test grid",
            $"; Machine: {machine.DisplayName}",
            $"; Powers (%): {string.Join(", ", powerPercents)}",
            $"; Speeds (mm/min): {string.Join(", ", speeds)}",
            $"; Each square is {cellSizeMm:0.#} mm; rows are power, columns are speed.",
            "G21", "G90", "G17",
            machine.Capabilities.HasFlag(MachineCapabilities.LaserMode) ? "M4 S0" : "M3 S0",
        };

        var step = cellSizeMm + gapMm;

        for (var row = 0; row < powerPercents.Length; row++)
        {
            var power = Math.Clamp(powerPercents[row], 0, 100);
            var spindle = machine.PowerToSpindle(power);

            for (var col = 0; col < speeds.Length; col++)
            {
                var speed = Math.Min(speeds[col], machine.MaxSpeedMmMin);
                var x0 = originX + col * step;
                var y0 = originY + row * step;

                lines.Add($"; {power:0.#}% @ {speed:0} mm/min");

                var square = new Polyline(
                [
                    new Vec2(x0, y0),
                    new Vec2(x0 + cellSizeMm, y0),
                    new Vec2(x0 + cellSizeMm, y0 + cellSizeMm),
                    new Vec2(x0, y0 + cellSizeMm),
                ], closed: true);

                var hatch = HatchFill.Generate([square], new HatchOptions
                {
                    SpacingMm = 0.12,
                    AngleDegrees = 0,
                    Bidirectional = true,
                });

                lines.AddRange(VectorEngraver.Generate(hatch, new VectorOptions
                {
                    FeedMmMin = speed,
                    TravelFeedMmMin = machine.TravelSpeedMmMin,
                    PowerPercent = power,
                    MaxSpindle = machine.MaxSpindleValue,
                    Passes = passes,
                    DynamicPower = machine.Capabilities.HasFlag(MachineCapabilities.LaserMode),
                    OptimiseTravel = false,
                    InsideOutFirst = false,
                    EmitHeader = false,
                }).Where(l => l is not ("G21" or "G90" or "M4 S0" or "M3 S0" or "M5")));
            }
        }

        lines.Add("M5");
        lines.Add("G0 X0 Y0");

        var toolpath = GcodeInterpreter.Interpret(lines, new InterpreterOptions { MaxSpindle = machine.MaxSpindleValue });
        var estimate = TimeEstimator.Estimate(toolpath, LimitsFromProfile(machine));
        var issues = JobValidator.Validate(toolpath, machine);

        var job = new JobDefinition
        {
            Name = $"Test grid {powerPercents.Length}×{speeds.Length}",
            Lines = lines,
            Bounds = toolpath.BurnBounds,
            EstimatedDuration = estimate.Total,
            MachineProfileId = machine.Id,
        };

        return new CamResult(job, toolpath, estimate, issues);
    }
}
