<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenBurn.Plugins\OpenBurn.Plugins.csproj" />
    <ProjectReference Include="..\..\src\OpenBurn.Core\OpenBurn.Core.csproj" />
    <ProjectReference Include="..\..\src\OpenBurn.Devices\OpenBurn.Devices.csproj" />
    <ProjectReference Include="..\..\src\OpenBurn.Transport\OpenBurn.Transport.csproj" />
    <ProjectReference Include="..\..\src\OpenBurn.Camera\OpenBurn.Camera.csproj" />
    <ProjectReference Include="..\..\src\OpenBurn.Materials\OpenBurn.Materials.csproj" />
    <ProjectReference Include="..\..\src\OpenBurn.Cam\OpenBurn.Cam.csproj" />
  </ItemGroup>

</Project>