<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OpenBurn.Core\OpenBurn.Core.csproj" />
    <ProjectReference Include="..\OpenBurn.Cam\OpenBurn.Cam.csproj" />
    <ProjectReference Include="..\OpenBurn.Devices\OpenBurn.Devices.csproj" />
    <ProjectReference Include="..\OpenBurn.Transport\OpenBurn.Transport.csproj" />
    <ProjectReference Include="..\OpenBurn.Camera\OpenBurn.Camera.csproj" />
    <ProjectReference Include="..\OpenBurn.Materials\OpenBurn.Materials.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
