using Emberline.Core.Documents;
using Emberline.Core.Geometry;
using Emberline.Core.Machines;
using Emberline.GCode;

namespace Emberline.Cam.Vector;

public sealed record VectorOptions
{
    public double FeedMmMin { get; init; } = 1000;
    public double TravelFeedMmMin { get; init; } = 6000;

    /// <summary>0–100.</summary>
    public double PowerPercent { get; init; } = 80;

    public int MaxSpindle { get; init; } = 1000;
    public int Passes { get; init; } = 1;

    /// <summary>M4 tracks feed rate, which stops corners over-burning on a cut.</summary>
    public bool DynamicPower { get; init; } = true;

    /// <summary>Reorder paths to shorten rapid travel.</summary>
    public bool OptimiseTravel { get; init; } = true;

    /// <summary>Cut nested contours before the shapes containing them.</summary>
    public bool InsideOutFirst { get; init; } = true;

    /// <summary>Lower Z by this much on each pass, for thick material. Zero on most diode lasers.</summary>
    public double ZStepPerPassMm { get; init; }

    public bool EmitHeader { get; init; } = true;

    public static readonly VectorOptions Default = new();
}

/// <summary>
/// Turns polylines into cut or outline-engrave G-code.
///
/// Two ordering decisions matter more than anything else in here. Travel
/// optimisation is the obvious one — unordered artwork spends most of its job time
/// moving between shapes rather than cutting. Inside-out ordering is the one people
/// only learn once: cut the outside of a ring before the hole and the part drops
/// through the honeycomb mid-job, and the head then ploughs into what is left.
/// </summary>
public static class VectorEngraver
{
    public static IReadOnlyList<string> Generate(IReadOnlyList<Polyline> paths, VectorOptions? options = null)
    {
        var o = options ?? VectorOptions.Default;
        var writer = new GcodeWriter();
        var spindle = (int)Math.Round(Math.Clamp(o.PowerPercent, 0, 100) / 100.0 * o.MaxSpindle);

        if (o.EmitHeader)
        {
            writer.Comment("Generated by Emberline");
            writer.Comment($"Vector: {paths.Count} path(s), {o.PowerPercent:0.#}% of S{o.MaxSpindle}, " +
                           $"{o.FeedMmMin:0} mm/min, {o.Passes} pass(es)");
        }

        writer.Raw("G21");
        writer.Raw("G90");
        writer.Raw(o.DynamicPower ? "M4 S0" : "M3 S0");

        var ordered = paths.Where(p => p.Count >= 2).ToList();
        if (ordered.Count == 0)
        {
            writer.Raw("M5");
            return writer.Lines;
        }

        if (o.InsideOutFirst) ordered = PathOps.InsideOutFirst(ordered);
        if (o.OptimiseTravel) ordered = PathOps.OptimiseTravel(ordered, Vec2.Zero);

        for (var pass = 0; pass < Math.Max(1, o.Passes); pass++)
        {
            if (pass > 0)
            {
                writer.Comment($"pass {pass + 1} of {o.Passes}");
                if (o.ZStepPerPassMm > 0)
                {
                    writer.Raw($"G91 G0 Z-{o.ZStepPerPassMm.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture)} G90");
                }
            }

            foreach (var path in ordered)
            {
                var start = path.First;

                // Arrive with the beam off, then switch on for the cut itself.
                writer.SetSpindle(0);
                writer.Rapid(start.X, start.Y, o.TravelFeedMmMin);

                for (var i = 1; i < path.Count; i++)
                {
                    writer.Linear(path[i].X, path[i].Y, spindle, o.FeedMmMin);
                }

                if (path.IsClosed) writer.Linear(start.X, start.Y, spindle, o.FeedMmMin);

                writer.SetSpindle(0);
            }
        }

        if (o.ZStepPerPassMm > 0 && o.Passes > 1)
        {
            var lift = o.ZStepPerPassMm * (o.Passes - 1);
            writer.Raw($"G91 G0 Z{lift.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture)} G90");
        }

        writer.SetSpindle(0);
        writer.Raw("M5");
        return writer.Lines;
    }

    /// <summary>Build the options for a layer, resolving percentages against the machine.</summary>
    public static VectorOptions OptionsFor(Layer layer, MachineProfile machine) => new()
    {
        FeedMmMin = Math.Min(layer.SpeedMmMin, machine.MaxSpeedMmMin),
        TravelFeedMmMin = machine.TravelSpeedMmMin,
        PowerPercent = layer.PowerPercent,
        MaxSpindle = machine.MaxSpindleValue,
        Passes = layer.Passes,
        DynamicPower = machine.Capabilities.HasFlag(MachineCapabilities.LaserMode),
        EmitHeader = false,
    };
}
